apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-app
  labels:
    app: k8s-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-sample-app
  template:
    metadata:
      labels:
        app: k8s-sample-app
    spec:
      containers:
        - name: k8s-sample-app
          image: nkdeveloper26/k8s-sample-app:latest # あとでDocker HubにPushしたタグを指定
          ports:
            - containerPort: 8080